owner_name: "WCNegentropy"
tagline: "Open Source • Developer Tools • AI Research • Regenerative Ventures"
email: "contact@wcnegentropy.com"
location: "New Jersey, USA"
github_user: "WCNegentropy"
avatar: "https://github.com/WCNegentropy.png"

social:
  github: "https://github.com/WCNegentropy"
  x: "https://twitter.com/WCNegentropy"
  huggingface: "https://huggingface.co/WCNegentropy"
  reddit: "https://www.reddit.com/r/WCNegentropy/"
  npm: "https://www.npmjs.com/package/@wcnegentropy/cli"
  linkedin: ""
  email: "mailto:contact@wcnegentropy.com"

products:
  - id: "prod-retro-vibecoder"
    name: "retro-vibecoder (UPG)"
    blurb: "Universal Project Generator — CLI tool and cross-platform Tauri desktop app that procedurally generates full working boilerplate tech stacks from a single deterministic seed. 40+ strategies, 7 archetypes, 12 languages."
    price: "Free / MIT"
    license: "MIT"
    image: "/images/products/UPG.png"
    highlights:
      - "Deterministic seed-based generation"
      - "40+ strategies, 12 languages"
      - "Cross-platform desktop app (Tauri)"
      - "npm install -g @wcnegentropy/cli"
    checkout: "https://github.com/WCNegentropy/retro-vibecoder"
    npm: "https://www.npmjs.com/package/@wcnegentropy/cli"
    coming_soon: false
    is_live: true
    featured: true

  - id: "prod-bit-transformer"
    name: "BitTransformerLM"
    blurb: "Experimental bit-level transformer with 9-bit encoding (8 data + 1 parity). Novel reversible architecture with built-in safety telemetry."
    price: "Research"
    license: "AGPLv3 - Research & Academic Use"
    image: "/images/products/bit-transformer.jpg"
    highlights:
      - "9-bit encoding system"
      - "Reversible architecture"
      - "Safety telemetry"
      - "793K-771M parameters"
    checkout: "https://huggingface.co/WCNegentropy/BitTransformerLM"
    coming_soon: false
    is_live: true

  - id: "prod-wrinkle-brane"
    name: "WrinkleBrane"
    blurb: "Experimental wave-interference memory system using 4D tensor operations. High-precision associative memory with parallel retrieval (150+ dB PSNR)."
    price: "Research"
    license: "AGPL-3.0 - Experimental Research"
    image: "/images/products/wrinkle-brane.jpg"
    highlights:
      - "4D tensor operations"
      - "Wave-interference memory"
      - "150+ dB PSNR"
      - "Parallel retrieval"
    checkout: "https://huggingface.co/WCNegentropy/WrinkleBrane"
    coming_soon: false
    is_live: true
